### ISSUE TITLE
University name not visible

### ISSUE THREAD

**Issue by aravindvnair99** [shangyilim/dsc-logo-generator#11]
Adding `Amrita School of Engineering, Bengaluru` or any long name is not possible. Ends up like this:

![DSC Amrita School of Engineering, Bengaluru Logo x1](https://user-images.githubusercontent.com/22199259/91131353-80636000-e6ca-11ea-9f74-882f11537145.png)

**Comment by aravindvnair99** [comment]
Seems like the bug is present here: https://dsc-logo-generator-e4903.web.app and not on https://dsc-logo-generator.web.app

**Comment by shangyilim** [comment]
Hi @aravindvnair99  please use  https://dsc-logo-generator.web.app instead. where did you get the other link from?

**Comment by aravindvnair99** [comment]
> Hi @aravindvnair99 please use https://dsc-logo-generator.web.app instead. where did you get the other link from?

@shangyilim That was the link provided on CLP.
