### ISSUE TITLE
Another Logo Format not supported

### ISSUE THREAD

**Issue by i-shivamsoni** [shangyilim/dsc-logo-generator#14]
There is another official logo format for the Student developer club logo, which is currently not supported by the logo generator.

![DSC XYZ University Light Vertical-Logo](https://user-images.githubusercontent.com/36334280/92151289-84b41980-ee3e-11ea-98d2-5aea38e62218.png)

**Comment by i-shivamsoni** [comment]
https://dsc-logo-generator.web.app/
solves the problem.

**Comment by Siddhant-K-code** [comment]
@i-shivamsoni 
![image](https://user-images.githubusercontent.com/55068936/95598014-0534ee00-0a6d-11eb-9ec8-4a413e06df7d.png)

Can't We Do Like This :))

**Comment by Siddhant-K-code** [comment]
But @shangyilim 
![image](https://user-images.githubusercontent.com/55068936/95598247-547b1e80-0a6d-11eb-9ce0-53f3cad020d0.png)
This Format is Not looking good, I Guess !

**Comment by Siddhant-K-code** [comment]
@shangyilim We Can Make That Square Resizable !?
